import{i as u,S as w,a as E}from"./assets/vendor-09d7c26e.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const i of t)if(i.type==="childList")for(const s of i.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&o(s)}).observe(document,{childList:!0,subtree:!0});function r(t){const i={};return t.integrity&&(i.integrity=t.integrity),t.referrerPolicy&&(i.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?i.credentials="include":t.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function o(t){if(t.ep)return;t.ep=!0;const i=r(t);fetch(t.href,i)}})();const g={error:{position:"topRight",class:"error",color:"white",timeout:3e3},info:{position:"topRight",timeout:3e3}},m={loading:"Loading images, please wait...",no_data:"Sorry, there are no images matching your search query. Please try again!",request_error:"Error during requesting",end_of_search:"We're sorry, but you've reached the end of search results."},f={error_no_data:{message:m.no_data,...g.error},request_error:{message:m.request_error,...g.error},end_of_search:{message:m.end_of_search,...g.info}};function q(){const a=document.createElement("button");return a.textContent="Load More",a.classList.add("btn"),a}function P(a){const e=document.createElement("div");return e.textContent=a,e.classList.add("loader"),e}function v(a){return a.reduce((e,r)=>(e+=T(r),e),"")}function T(a){const{id:e,webformatURL:r,largeImageURL:o,tags:t,likes:i,views:s,comments:_,downloads:S}=a;return`
    <div data-image-id="${e}" class="image">
      <a class="image-link" href="${o}">
        <div class="image-photo-wrap"><img class="image-photo" src="${r}" data-source="${o}" alt="${t}"/></div>
        <div class="image-data">
          <div class="image-data-item image-data-item-likes"><div class="image-data-item-label">Likes</div><div class="image-data-item-number">${i}</div></div>
          <div class="image-data-item image-data-item-views"><div class="image-data-item-label">Views</div><div class="image-data-item-number">${s}</div></div>
          <div class="image-data-item image-data-item-comments"><div class="image-data-item-label">Comments</div><div class="image-data-item-number">${_}</div></div>
          <div class="image-data-item image-data-item-downloads"><div class="image-data-item-label">Downloads</div><div class="image-data-item-number">${S}</div></div>
      </div>
      </a>
    </div>
  `}function x(a){return a[0].id??null}function M(a){const e=document.querySelectorAll(`[data-image-id="${a}"]`);if(!e)return;const r=e[e.length-1];setTimeout(()=>{r.scrollIntoView({behavior:"smooth",block:"start"})},200)}const d=document.querySelector("#search-form"),h=P(m.loading),l=document.querySelector("#images"),c=q(),y=d.querySelector('input[name="search"]');let p,n=1;const L=15;function $(){p?p.refresh():p=new w("#images .image-link",{captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250})}async function I(a){return await E.get("https://pixabay.com/api/",{params:{key:"43799735-9794f2fe47020c8ff64ba54b4",q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,page:n,per_page:L}})}async function b(a,e=!1){e&&(n=1,l.innerHTML="");try{const r=await I(a),{hits:o,totalHits:t}=r.data;if(t<1){u.error(f.error_no_data),d.reset();return}const i=x(o),s=Math.ceil(t/L);c.remove(),e?l.innerHTML=v(o):l.insertAdjacentHTML("beforeend",v(o)),i&&M(i),n<s?(l.appendChild(c),n++):(e||u.info(f.end_of_search),d.reset(),n=1),$()}catch(r){console.log(r),u.error(f.request_error)}}document.addEventListener("DOMContentLoaded",a=>{d.addEventListener("submit",async e=>{e.preventDefault(),d.after(h);const r=y.value;await b(r,!0),h.remove()}),c.addEventListener("click",async()=>{const e=y.value;c.classList.add("loading"),await b(e),c.classList.remove("loading")})});
//# sourceMappingURL=commonHelpers.js.map
